version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    
    volumes:
      - /home:/srv
      - /home/docker/filebrowser/filebrowser.db:/database/filebrowser.db
      - /home/docker/filebrowser/settings.json:/config/settings.json    

    ports:
      - '8082:80'
    restart: unless-stopped