version: '3.5'

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Paris
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /home/docker/jellyseer/config:/app/config
    restart: unless-stopped