version: "3"

services:

  n8n:
    image: n8nio/n8n
    container_name: n8n
    environment:
      N8N_SECURE_COOKIE: false
    volumes:
      - /home/docker/n8n:/home/node/.n8n
    ports:
      - 5678:5678
    restart: unless-stopped